// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.3
// source: protob/ecdsa-blind-setup.proto

package setup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SURound1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimeShare []byte `protobuf:"bytes,1,opt,name=prime_share,json=primeShare,proto3" json:"prime_share,omitempty"`
}

func (x *SURound1Message) Reset() {
	*x = SURound1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protob_ecdsa_blind_setup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SURound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SURound1Message) ProtoMessage() {}

func (x *SURound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_blind_setup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SURound1Message.ProtoReflect.Descriptor instead.
func (*SURound1Message) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_blind_setup_proto_rawDescGZIP(), []int{0}
}

func (x *SURound1Message) GetPrimeShare() []byte {
	if x != nil {
		return x.PrimeShare
	}
	return nil
}

type SURound2Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GamaShare []byte `protobuf:"bytes,1,opt,name=gama_share,json=gamaShare,proto3" json:"gama_share,omitempty"`
}

func (x *SURound2Message) Reset() {
	*x = SURound2Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protob_ecdsa_blind_setup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SURound2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SURound2Message) ProtoMessage() {}

func (x *SURound2Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_blind_setup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SURound2Message.ProtoReflect.Descriptor instead.
func (*SURound2Message) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_blind_setup_proto_rawDescGZIP(), []int{1}
}

func (x *SURound2Message) GetGamaShare() []byte {
	if x != nil {
		return x.GamaShare
	}
	return nil
}

type SURound3Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimeMask []byte `protobuf:"bytes,1,opt,name=prime_mask,json=primeMask,proto3" json:"prime_mask,omitempty"`
}

func (x *SURound3Message) Reset() {
	*x = SURound3Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protob_ecdsa_blind_setup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SURound3Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SURound3Message) ProtoMessage() {}

func (x *SURound3Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_blind_setup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SURound3Message.ProtoReflect.Descriptor instead.
func (*SURound3Message) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_blind_setup_proto_rawDescGZIP(), []int{2}
}

func (x *SURound3Message) GetPrimeMask() []byte {
	if x != nil {
		return x.PrimeMask
	}
	return nil
}

var File_protob_ecdsa_blind_setup_proto protoreflect.FileDescriptor

var file_protob_ecdsa_blind_setup_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x2f, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2d, 0x62,
	0x6c, 0x69, 0x6e, 0x64, 0x2d, 0x73, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1b, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62,
	0x2e, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x22, 0x32, 0x0a,
	0x0f, 0x53, 0x55, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x22, 0x30, 0x0a, 0x0f, 0x53, 0x55, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x61, 0x5f, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x61, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x22, 0x30, 0x0a, 0x0f, 0x53, 0x55, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x33, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f,
	0x6d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d,
	0x65, 0x4d, 0x61, 0x73, 0x6b, 0x42, 0x13, 0x5a, 0x11, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2d, 0x62,
	0x6c, 0x69, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x74, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protob_ecdsa_blind_setup_proto_rawDescOnce sync.Once
	file_protob_ecdsa_blind_setup_proto_rawDescData = file_protob_ecdsa_blind_setup_proto_rawDesc
)

func file_protob_ecdsa_blind_setup_proto_rawDescGZIP() []byte {
	file_protob_ecdsa_blind_setup_proto_rawDescOnce.Do(func() {
		file_protob_ecdsa_blind_setup_proto_rawDescData = protoimpl.X.CompressGZIP(file_protob_ecdsa_blind_setup_proto_rawDescData)
	})
	return file_protob_ecdsa_blind_setup_proto_rawDescData
}

var file_protob_ecdsa_blind_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protob_ecdsa_blind_setup_proto_goTypes = []interface{}{
	(*SURound1Message)(nil), // 0: binance.tsslib.ecdsa.keygen.SURound1Message
	(*SURound2Message)(nil), // 1: binance.tsslib.ecdsa.keygen.SURound2Message
	(*SURound3Message)(nil), // 2: binance.tsslib.ecdsa.keygen.SURound3Message
}
var file_protob_ecdsa_blind_setup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protob_ecdsa_blind_setup_proto_init() }
func file_protob_ecdsa_blind_setup_proto_init() {
	if File_protob_ecdsa_blind_setup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protob_ecdsa_blind_setup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SURound1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protob_ecdsa_blind_setup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SURound2Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protob_ecdsa_blind_setup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SURound3Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protob_ecdsa_blind_setup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protob_ecdsa_blind_setup_proto_goTypes,
		DependencyIndexes: file_protob_ecdsa_blind_setup_proto_depIdxs,
		MessageInfos:      file_protob_ecdsa_blind_setup_proto_msgTypes,
	}.Build()
	File_protob_ecdsa_blind_setup_proto = out.File
	file_protob_ecdsa_blind_setup_proto_rawDesc = nil
	file_protob_ecdsa_blind_setup_proto_goTypes = nil
	file_protob_ecdsa_blind_setup_proto_depIdxs = nil
}
